
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Addelephant extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;

    /**
     * Creates new form Addelephant
     */
    public Addelephant() {
        initComponents();
        conn=DBconnect.getConnection();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txteleid = new javax.swing.JTextField();
        genderbox = new javax.swing.JComboBox<>();
        wpabox = new javax.swing.JComboBox<>();
        yearbox = new javax.swing.JComboBox<>();
        herdbox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 166, 82));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add elephant Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 286, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Elephant ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Elephant gender");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("WPA Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Year");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Herd Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(191, 139, 103));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        txteleid.setBackground(new java.awt.Color(255, 248, 154));
        txteleid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txteleid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteleidActionPerformed(evt);
            }
        });
        jPanel1.add(txteleid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        genderbox.setBackground(new java.awt.Color(255, 205, 221));
        genderbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderbox.setForeground(new java.awt.Color(51, 51, 51));
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        wpabox.setBackground(new java.awt.Color(255, 205, 221));
        wpabox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wpabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Udawalawa", "Lunugamvehere", "Yala", "Boondala", "Maththala", "Sinharaja", "Adams Peak", "Minneriya Kavudulla Hurulu reserve", "Wilpattu", "Kala wewa" }));
        jPanel1.add(wpabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, -1));

        yearbox.setBackground(new java.awt.Color(255, 205, 221));
        yearbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017" }));
        jPanel1.add(yearbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        herdbox.setBackground(new java.awt.Color(255, 205, 221));
        herdbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        herdbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "" }));
        jPanel1.add(herdbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jButton2.setBackground(new java.awt.Color(240, 84, 84));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Close");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addelephant.png"))); // NOI18N
        jPanel2.add(jLabel7);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 410, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String eleid;
     String elegender;
     String wpaname;
     int year;
     int herdid;                                      //code to insert elephant details
     eleid = txteleid.getText();
     elegender= genderbox.getSelectedItem().toString();
     wpaname= wpabox.getSelectedItem().toString();
     year= Integer.parseInt(yearbox.getSelectedItem().toString());
     herdid=Integer.parseInt(herdbox.getSelectedItem().toString());
         try {
            String sql="INSERT INTO elephant(Eleid,Ele_gender,WPA_Name,Year,Herdid) VALUES('"+eleid+"','"+elegender+"','"+wpaname+"','"+year+"','"+herdid+"')";
            pst= conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Successfully registered");
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            }

    




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Wildrdashboard wildrdash = new Wildrdashboard(); //opens wildr dashboard
     wildrdash.setVisible(true);
     this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txteleidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteleidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteleidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addelephant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addelephant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addelephant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addelephant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addelephant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JComboBox<String> herdbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txteleid;
    private javax.swing.JComboBox<String> wpabox;
    private javax.swing.JComboBox<String> yearbox;
    // End of variables declaration//GEN-END:variables
}
