
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Wildrdashboard extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs= null;

    /**
     * Creates new form Wildrdashboard
     */
    public Wildrdashboard() {
        initComponents();
        conn= DBconnect.getConnection();
        tableload();
    }
    
    public void tableload(){
        try {
            String sql="SELECT Eleid, Ele_gender,WPA_Name,Year, Herdid FROM elephant";
            pst= conn.prepareStatement(sql);
            rs= pst.executeQuery();
            tbl1.setModel(DbUtils.resultSetToTableModel(rs));
            //tableload();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    public void tabledata() {
        int r=tbl1.getSelectedRow();
        
        String Eleid = tbl1.getValueAt(r,0).toString();
        String Ele_gender = tbl1.getValueAt(r,1).toString();
        String WPA_Name= tbl1.getValueAt(r,2).toString();
        String Year = tbl1.getValueAt(r,3).toString();
        String Herdid = tbl1.getValueAt(r,4).toString();
        
        Eleidbox.setText(Eleid);
        Elegenderbox.setSelectedItem(Ele_gender);
        wpabox.setSelectedItem(WPA_Name);
        yearbox.setSelectedItem(Year);
        herdidbox.setSelectedItem(Herdid);
        
    }
    public void search(){
        String Search=searchbox.getText();
        try {
            String sql= "SELECT * FROM elephant WHERE Eleid LIKE '%"+Search+"%' OR WPA_Name LIKE '%"+Search+"%' OR Year LIKE '%"+Search+"%'";
      
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NO result found");
        }
    }
    public void update(){
         String Ele_id=Eleidbox.getText();
        String Ele_gender = Elegenderbox.getSelectedItem().toString();
        String WPA_Name= wpabox.getSelectedItem().toString();
        String Year = yearbox.getSelectedItem().toString();
        String Herdid = herdidbox.getSelectedItem().toString();
        try {
            String sql="UPDATE elephant SET Ele_gender='"+Ele_gender+"',WPA_Name='"+WPA_Name+"',Year='"+Year+"',Herdid='"+Herdid+"' WHERE Eleid='"+Ele_id+"'";
            pst= conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        
        }
        
       tableload();
    }
   
    
    public void clear(){
        Eleidbox.setText("");
        Elegenderbox.setSelectedIndex(0);
        wpabox.setSelectedIndex(0);
        yearbox.setSelectedIndex(0);
        herdidbox.setSelectedIndex(0);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Eleidbox = new javax.swing.JTextField();
        searchbox = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        herdidbox = new javax.swing.JComboBox<>();
        Elegenderbox = new javax.swing.JComboBox<>();
        wpabox = new javax.swing.JComboBox<>();
        yearbox = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 166, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ele_id", "Ele_gender", "WPA_Name", "Year", "Herdid"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 600, 200));

        jButton1.setBackground(new java.awt.Color(250, 187, 81));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add elephants");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jButton3.setBackground(new java.awt.Color(250, 187, 81));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        jButton4.setBackground(new java.awt.Color(250, 187, 81));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Migration");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jButton6.setBackground(new java.awt.Color(240, 84, 84));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Logout");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 90, -1));

        Eleidbox.setBackground(new java.awt.Color(231, 251, 190));
        Eleidbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Eleidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 110, -1));

        searchbox.setBackground(new java.awt.Color(231, 251, 190));
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jButton7.setBackground(new java.awt.Color(255, 211, 154));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Search");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        herdidbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        herdidbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "" }));
        jPanel1.add(herdidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        Elegenderbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Elegenderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(Elegenderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        wpabox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wpabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Udawalawa", "Lunugamvehere", "Yala", "Boondala", "Maththala", "Sinharaja", "Adams Peak", "Minneriya Kavudulla Hurulu reserve", "Wilpattu", "Kala wewa" }));
        jPanel1.add(wpabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 340, -1));

        yearbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017" }));
        jPanel1.add(yearbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jButton5.setBackground(new java.awt.Color(250, 187, 81));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Update");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jButton8.setBackground(new java.awt.Color(250, 187, 81));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Home home= new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Addelephant addelephant = new Addelephant();
        addelephant.setVisible(true);
        this.setVisible(false);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        // TODO add your handling code here:
        tabledata();
    }//GEN-LAST:event_tbl1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchboxKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        migrationgui miga= new migrationgui();
        miga.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int check= JOptionPane.showConfirmDialog(null,"Do you need to delete the selected data permanently?");
        if (check==0){
            String Ele_id = Eleidbox.getText();
            try {
                String sql ="DELETE  FROM elephant WHERE Eleid='"+Ele_id+"'";
                pst= conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Deleted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        tableload();
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wildrdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wildrdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wildrdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wildrdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wildrdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Elegenderbox;
    private javax.swing.JTextField Eleidbox;
    private javax.swing.JComboBox<String> herdidbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTable tbl1;
    private javax.swing.JComboBox<String> wpabox;
    private javax.swing.JComboBox<String> yearbox;
    // End of variables declaration//GEN-END:variables
}
